name: Docker Image CI

on:
  push:
    tags:
     - 'v*.*.*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        push: true
        context: .
        file: ./Dockerfile
        tags: |
          ghcr.io/g-core/cert-manager-webhook-gcore:latest
          ghcr.io/g-core/cert-manager-webhook-gcore:${{ github.ref }}